"""
List of Common Backchannel keywords and phrases.
"""

backchannel = ['oh great',
               'oh my word',
               'oh yes',
               "that's good",
               'oh goodness',
               'right',
               'oh gosh',
               'yeah uh',
               'well good',
               "that's interesting",
               'yep',
               'that s nice',
               'uh',
               'huh-uh',
               'that s okay',
               'oh my gosh',
               'Mmm',
               "that's great",
               'oh my goodness',
               'no',
               'that s right',
               'okay',
               'ooh',
               'oh uh-huh',
               'uh-huh',
               'so yeah',
               'wow',
               'really',
               'that s true',
               'true',
               'um yeah',
               'all right',
               'oh yeah',
               'oh',
               'my goodness',
               'i bet',
               'great',
               'oh no',
               'well yeah',
               'um uh huh',
               'huh uh',
               'oh really',
               'oh okay',
               'good',
               "that's right",
               'gosh',
               "that's neat",
               'oh gee',
               'pardon me',
               'jeez',
               'oh sure',
               'is it',
               'exactly',
               'is that right',
               'oh good',
               'Hm',
               'oh my',
               'oh dear',
               'uh yeah',
               'um',
               'oh uh huh',
               'what',
               "that's okay",
               'Hmmm',
               'oh i see',
               'oh boy',
               'Mhh',
               'oh wow',
               'that s great',
               "that's true",
               'i know',
               'Hmm',
               'sure',
               'that s neat',
               'boy',
               'that s good',
               'you bet',
               'uh huh',
               'i see',
               'you know',
               'huh',
               'there you go',
               'do you',
               "that's nice",
               'that s interesting',
               'yes',
               'i understand',
               'yeah',
               'um uh-huh']
